apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: finflow
spec:
  replicas: 2
  selector:
    matchLabels: {app: account-service}
  template:
    metadata:
      labels: {app: account-service}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          image: finflow/account-service:1.0.0
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet: {path: /actuator/health/readiness, port: 8083}
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: 8083}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: {cpu: 200m, memory: 256Mi}
            limits: {cpu: '1', memory: 768Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: finflow
spec:
  selector: {app: account-service}
  ports:
    - port: 8083
      targetPort: 8083
